### ISSUE TITLE
Doubt regarding stats for Cameo and Mempod

### ISSUE THREAD

**Issue by Upasna55** [yousei-github/ChampSim-Ramulator#6]
Dear Yousei

I've collected stats for Ideal Cameo, Colocated Cameo, and Mempod for single core, 2 cores, and 4 cores. But, the stats for all these three configurations are exactly same. I've used 1 Million warmup Instructions and 10 Million Simulation Instructions. Further, the ramulator stats are also coming up exactly same, wherein memory-2 stats are all zero. Can you please share your insights for such a behavior?   

Thanks & Regards
Upasna

**Comment by yousei-github** [comment]
@Y-Mizuno-github @COLLAGE-TG

Hey, guys. Do you have time to check it?

**Comment by yousei-github** [comment]
Oh, I see. If you check the hit rate, you will find that it is 1.00, which means the first memory serves all memory requests. The reason is that the memory footprint (`main memory footprint`) of the chosen benchmark is not enough to cover the second memory.

So, if you want to run the memory-2, you can decrease the capacity of the first memory or select the benchmark with a large memory footprint.

**Comment by Upasna55** [comment]
Got it Yousei. Thank you.
